import { arrowRightIcon } from '../theme/utils/icons';

export const v5 = {
    '/v5/en/': [
        {
            text: 'Introduction',
            items: [
                { text: 'Getting Started', link: '/v5/en/' },
                { text: 'Authentication', link: '/v5/en/authentication' },
            ],
        },
        {
            text: 'Endpoints',
            items: [
                { text: 'Address', link: '/v5/en/address', badge: 'GET' },
                { text: 'Agent', link: '/v5/en/agent', badge: 'GET' },
                { text: 'Algorithms', link: '/v5/en/algorithms', badge: 'GET' },
                { text: 'Asymmetric', link: '/v5/en/asymmetric', badge: 'POST' },
                { text: 'Avatar', link: '/v5/en/avatar', badge: 'GET' },
                { text: 'Barcode', link: '/v5/en/barcode', badge: 'GET' },
                { text: 'Captcha', link: '/v5/en/captcha', badge: 'GET' },
                { text: 'Chart', link: '/v5/en/chart', badge: 'POST' },
                {
                    text: 'Chat',
                    collapsed: true,
                    items: [
                        { text: '/v5/chat', link: '/v5/en/chat', badge: 'POST' },
                        { text: '/v5/chat', link: '/v5/en/chat/messages', badge: 'GET' },
                        {
                            text: '/v5/chat/:token',
                            link: '/v5/en/chat/clear',
                            badge: 'DELETE',
                        },
                        {
                            text: '/v5/chat/private',
                            link: '/v5/en/chat/private',
                            badge: 'POST',
                        },
                    ],
                },
                { text: 'Color', link: '/v5/en/color', badge: 'GET' },
                { text: 'Convert', link: '/v5/en/convert', badge: 'GET' },
                { text: 'Credit', link: '/v5/en/credit', badge: 'GET' },
                { text: 'Cron', link: '/v5/en/cron', badge: 'GET' },
                { text: 'Dice', link: '/v5/en/dice', badge: 'GET' },
                { text: 'Domain', link: '/v5/en/domain', badge: 'GET' },
                { text: 'Encode', link: '/v5/en/encode', badge: 'GET' },
                { text: 'Evaluate', link: '/v5/en/evaluate', badge: 'GET' },
                { text: 'Geo', link: '/v5/en/geo', badge: 'GET' },
                { text: 'Hash', link: '/v5/en/hash', badge: 'POST' },
                { text: 'Headers', link: '/v5/en/headers', badge: 'GET' },
                { text: 'Hyperplanning', link: '/v5/en/hyperplanning', badge: 'POST' },
                { text: 'IP', link: '/v5/en/ip', badge: 'GET' },
                { text: 'Infos', link: '/v5/en/infos', badge: 'GET' },
                { text: 'Levenshtein', link: '/v5/en/levenshtein', badge: 'GET' },
                { text: 'Matrix', link: '/v5/en/matrix', badge: 'POST' },
                { text: 'OTP', link: '/v5/en/otp', badge: 'POST' },
                { text: 'Palette', link: '/v5/en/palette', badge: 'GET' },
                { text: 'Password', link: '/v5/en/password', badge: 'GET' },
                { text: 'Personal', link: '/v5/en/personal', badge: 'GET' },
                { text: 'Placeholder', link: '/v5/en/placeholder', badge: 'GET' },
                { text: 'QR Code', link: '/v5/en/qrcode', badge: 'GET' },
                { text: 'Regex', link: '/v5/en/regex', badge: 'GET' },
                { text: 'Statistics', link: '/v5/en/statistics', badge: 'GET' },
                { text: 'Symmetric', link: '/v5/en/symmetric', badge: 'POST' },
                { text: 'Text', link: '/v5/en/text', badge: 'GET' },
                {
                    text: 'Tic-Tac-Toe',
                    collapsed: true,
                    items: [
                        {
                            text: '/v5/tic-tac-toe',
                            link: '/v5/en/tic-tac-toe',
                            badge: 'POST',
                        },
                        {
                            text: '/v5/tic-tac-toe/:game',
                            link: '/v5/en/tic-tac-toe/play',
                            badge: 'PATCH',
                        },
                        {
                            text: '/v5/tic-tac-toe/:game',
                            link: '/v5/en/tic-tac-toe/forfeit',
                            badge: 'DELETE',
                        },
                        {
                            text: '/v5/tic-tac-toe/fetch',
                            link: '/v5/en/tic-tac-toe/fetch',
                            badge: 'POST',
                        },
                        {
                            text: '/v5/tic-tac-toe/list',
                            link: '/v5/en/tic-tac-toe/list',
                            badge: 'POST',
                        },
                    ],
                },
                { text: 'Time', link: '/v5/en/time', badge: 'GET' },
                { text: 'Token', link: '/v5/en/token', badge: 'POST' },
                { text: 'Username', link: '/v5/en/username', badge: 'GET' },
                { text: 'Validate', link: '/v5/en/validate', badge: 'GET' },
            ],
        },
        {
            text: 'Tools',
            items: [
                { text: 'Playground', link: '/v5/en/playground' },
                {
                    text: 'Changelog',
                    collapsed: true,
                    items: [
                        { text: 'Overview', link: '/v5/en/changelog' },
                        { text: '5.2.0', link: '/v5/en/changelog/5.2.0' },
                        { text: '5.1.0', link: '/v5/en/changelog/5.1.0' },
                        { text: '5.0.0', link: '/v5/en/changelog/5.0.0' },
                        { text: `Previous version ${arrowRightIcon}`, link: '/v4/en/changelog' },
                    ],
                },
            ],
        },
        {
            text: 'Other',
            items: [{ text: 'Pricing', link: '/v5/en/pricing' }],
        },
    ],
    '/v5/fr/': [
        {
            text: 'Introduction',
            items: [
                { text: 'Commencer', link: '/v5/fr/' },
                { text: 'Authentification', link: '/v5/fr/authentication' },
            ],
        },
        {
            text: 'Endpoints',
            items: [
                { text: 'Address', link: '/v5/fr/address', badge: 'GET' },
                { text: 'Agent', link: '/v5/fr/agent', badge: 'GET' },
                { text: 'Algorithms', link: '/v5/fr/algorithms', badge: 'GET' },
                { text: 'Asymmetric', link: '/v5/fr/asymmetric', badge: 'POST' },
                { text: 'Avatar', link: '/v5/fr/avatar', badge: 'GET' },
                { text: 'Barcode', link: '/v5/fr/barcode', badge: 'GET' },
                { text: 'Captcha', link: '/v5/fr/captcha', badge: 'GET' },
                { text: 'Chart', link: '/v5/fr/chart', badge: 'POST' },
                {
                    text: 'Chat',
                    collapsed: true,
                    items: [
                        { text: '/v5/chat', link: '/v5/fr/chat', badge: 'POST' },
                        { text: '/v5/chat', link: '/v5/fr/chat/messages', badge: 'GET' },
                        {
                            text: '/v5/chat/:token',
                            link: '/v5/fr/chat/clear',
                            badge: 'DELETE',
                        },
                        {
                            text: '/v5/chat/private',
                            link: '/v5/fr/chat/private',
                            badge: 'POST',
                        },
                    ],
                },
                { text: 'Color', link: '/v5/fr/color', badge: 'GET' },
                { text: 'Convert', link: '/v5/fr/convert', badge: 'GET' },
                { text: 'Credit', link: '/v5/fr/credit', badge: 'GET' },
                { text: 'Cron', link: '/v5/fr/cron', badge: 'GET' },
                { text: 'Dice', link: '/v5/fr/dice', badge: 'GET' },
                { text: 'Domain', link: '/v5/fr/domain', badge: 'GET' },
                { text: 'Encode', link: '/v5/fr/encode', badge: 'GET' },
                { text: 'Evaluate', link: '/v5/fr/evaluate', badge: 'GET' },
                { text: 'Geo', link: '/v5/fr/geo', badge: 'GET' },
                { text: 'Hash', link: '/v5/fr/hash', badge: 'POST' },
                { text: 'Headers', link: '/v5/fr/headers', badge: 'GET' },
                { text: 'Hyperplanning', link: '/v5/fr/hyperplanning', badge: 'POST' },
                { text: 'IP', link: '/v5/fr/ip', badge: 'GET' },
                { text: 'Infos', link: '/v5/fr/infos', badge: 'GET' },
                { text: 'Levenshtein', link: '/v5/fr/levenshtein', badge: 'GET' },
                { text: 'Matrix', link: '/v5/fr/matrix', badge: 'POST' },
                { text: 'OTP', link: '/v5/fr/otp', badge: 'POST' },
                { text: 'Palette', link: '/v5/fr/palette', badge: 'GET' },
                { text: 'Password', link: '/v5/fr/password', badge: 'GET' },
                { text: 'Personal', link: '/v5/fr/personal', badge: 'GET' },
                { text: 'Placeholder', link: '/v5/fr/placeholder', badge: 'GET' },
                { text: 'QR Code', link: '/v5/fr/qrcode', badge: 'GET' },
                { text: 'Regex', link: '/v5/fr/regex', badge: 'GET' },
                { text: 'Statistics', link: '/v5/fr/statistics', badge: 'GET' },
                { text: 'Symmetric', link: '/v5/fr/symmetric', badge: 'POST' },
                { text: 'Text', link: '/v5/fr/text', badge: 'GET' },
                {
                    text: 'Tic-Tac-Toe',
                    collapsed: true,
                    items: [
                        {
                            text: '/v5/tic-tac-toe',
                            link: '/v5/fr/tic-tac-toe',
                            badge: 'POST',
                        },
                        {
                            text: '/v5/tic-tac-toe/:game',
                            link: '/v5/fr/tic-tac-toe/play',
                            badge: 'PATCH',
                        },
                        {
                            text: '/v5/tic-tac-toe/:game',
                            link: '/v5/fr/tic-tac-toe/forfeit',
                            badge: 'DELETE',
                        },
                        {
                            text: '/v5/tic-tac-toe/fetch',
                            link: '/v5/fr/tic-tac-toe/fetch',
                            badge: 'POST',
                        },
                        {
                            text: '/v5/tic-tac-toe/list',
                            link: '/v5/fr/tic-tac-toe/list',
                            badge: 'POST',
                        },
                    ],
                },
                { text: 'Time', link: '/v5/fr/time', badge: 'GET' },
                { text: 'Token', link: '/v5/fr/token', badge: 'POST' },
                { text: 'Username', link: '/v5/fr/username', badge: 'GET' },
                { text: 'Validate', link: '/v5/fr/validate', badge: 'GET' },
            ],
        },
        {
            text: 'Outils',
            items: [
                { text: 'Playground', link: '/v5/fr/playground' },
                {
                    text: 'Changelog',
                    collapsed: true,
                    items: [
                        { text: 'Aperçu', link: '/v5/fr/changelog' },
                        { text: '5.2.0', link: '/v5/fr/changelog/5.2.0' },
                        { text: '5.1.0', link: '/v5/fr/changelog/5.1.0' },
                        { text: '5.0.0', link: '/v5/fr/changelog/5.0.0' },
                        { text: `Version précédente ${arrowRightIcon}`, link: '/v4/fr/changelog' },
                    ],
                },
            ],
        },
        {
            text: 'Autre',
            items: [{ text: 'Tarification', link: '/v5/fr/pricing' }],
        },
    ],
};
